{% set version = "0.3.8" %}

package:
  name: thex
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/i/imagesize/imagesize-{{ version }}.tar.gz

build:
  noarch: python
  number: 0.0.0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

# test:
#   imports:
#     - imagesize

about:
  # home: https://github.com/shibukawa/imagesize_py
  license: MIT
  summary: 'THEx'
  description: |
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
  # dev_url: https://github.com/shibukawa/imagesize_py
  # doc_url: https://pypi.python.org/pypi/imagesize
  # doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst