{% set version = "0.3.8" %}

package:
  name: thex
  version: {{ version }}

source:
  url: https://github.com/harris-2374/conda-dash-app.git

build:
  noarch: python
  number: 0.0.1
  entry_points:
    - thex src.thex:main

requirements:
  host:
    - python
    - pip
    - conda
    - setuptools

  run:
    - python
    # - dash
    # - dash-bootstrap-components
    # - ete3
    # - biopython
    # - pandas
    # - openpyxl


about:
  # home: https://github.com/shibukawa/imagesize_py
  license: MIT
  summary: 'thex'
  description: ''
  # dev_url: https://github.com/shibukawa/imagesize_py
  # doc_url: https://pypi.python.org/pypi/imagesize
  # doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst